backend:
  name: github
  repo: rmnmatusevich/online-shop-gatsby
  branch: dev
media_folder: static/img
public_folder: img
collections:
  - name: "content"
    label: "Content"
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle}
      - { name: titleen, label: Title-en }
      - { name: subtitleen, label: Subtitle-en}
      - { name: titlepl, label: Title-pl }
      - { name: subtitlepl, label: Subtitle-pl}
      - { label: "BackgroundImage", name: "backgroundImage", widget: "image", required: true }
      - { name: openingTitle, label: OpeningTitle, widget: string }
      - { name: openingDescription, label: OpeningDescription, widget: markdown }
      - { name: aboutUsTitle, label: AboutUsTitle, widget: string }
      - { name: aboutUsDescription, label: AboutUsDescription, widget: markdown }
      - { name: openingTitleen, label: OpeningTitle-en, widget: string }
      - { name: openingDescriptionen, label: OpeningDescription-en, widget: markdown }
      - { name: aboutUsTitleen, label: AboutUsTitle-en, widget: string }
      - { name: aboutUsDescriptionen, label: AboutUsDescription-en, widget: markdown }
      - { name: openingTitlepl, label: OpeningTitle-pl, widget: string }
      - { name: openingDescriptionpl, label: OpeningDescription-pl, widget: markdown }
      - { name: aboutUsTitlepl, label: AboutUsTitle-pl, widget: string }
      - { name: aboutUsDescriptionpl, label: AboutUsDescription-pl, widget: markdown }
      - label: 'Carousel'
        name: "carousel"
        widget: list
        fields:
          - { label: "Image", name: "image", widget: "image"}
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: repair
    label: Repair
    folder: repair
    create: true
    fields:
      - { name: "path", label: "Path", required: true }
      - { name: "type", label: "Type", widget: "string", required: true }
      - { label: "productImage", name: "productImage", widget: "image", required: true }
      - { label: "productName", name: "productName", widget: "string", required: true }
      - { label: "productBrand", name: "productBrand", widget: "string", required: true }
      - { label: "productDescription", name: "productDescription", widget: "markdown", required: true }
      - { label: "productDescription-en", name: "productDescriptionen", widget: "markdown", required: true }
      - { label: "productDescription-pl", name: "productDescriptionpl", widget: "markdown", required: true }
      - { label: "productYear", name: "productYear", widget: "number", default: 2020, value_type: "int", required: true }
      - label: 'Services'
        name: "services"
        widget: list
        fields:
        - { label: "ServiceIcon", name: "serviceIcon", widget: "image", required: true }
        - { label: "ServiceTitle", name: "serviceTitle", widget: "markdown", required: true }
        - { label: "ServiceTitle-en", name: "serviceTitleen", widget: "markdown", required: true }
        - { label: "ServiceTitle-pl", name: "serviceTitlepl", widget: "markdown", required: true }
        - { label: "ServiceCost", name: "serviceCost", widget: "string", required: true }
  - name: repairPage
    label: RepairPage
    folder: repair-page
    create: true
    fields:
      - { name: path, label: Path, required: true  }
      - { name: title, label: Title, required: true  }
      - { name: titleen, label: Title-en, required: true  }
      - { name: titlepl, label: Title-pl, required: true  }
      - { name: subtitle, label: Subtitle, required: true }
      - { name: subtitleen, label: Subtitle-en, required: true }
      - { name: subtitlepl, label: Subtitle-pl, required: true }
      - { name: repair, label: Repair, default: "/repair", widget: "string", required: true }
      - { label: "BackgroundImage", name: "backgroundImage", widget: "image", required: true }
      - label: 'Brands'
        name: "brands"
        widget: list
        fields:
          - { label: "Brand", name: "brand", widget: "string", required: true }
          - { label: "Image", name: "image", widget: "image", required: true }
          - {label: "LinkTo", name: "linkTo", widget: "string", required: true }
  - name: sellPage
    label: SellPage
    folder: sell-page
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: title, label: Title, required: true  }
      - { name: titleen, label: Title-en, required: true  }
      - { name: titlepl, label: Title-pl, required: true  }
      - { name: subtitle, label: Subtitle, required: true }
      - { name: subtitleen, label: Subtitle-en, required: true }
      - { name: subtitlepl, label: Subtitle-pl, required: true }
      - { label: "BackgroundImage", name: "backgroundImage", widget: "image", required: true }
      - { name: sellTitle, label: SellTitle, widget: "string", required: true }
      - { name: sellTitleen, label: SellTitle-en, widget: "string", required: true }
      - { name: sellTitlepl, label: SellTitle-pl, widget: "string", required: true }
      - { name: sellText, label: SellText, widget: "markdown", required: true }
      - { name: sellTexten, label: SellText-en, widget: "markdown", required: true }
      - { name: sellTextpl, label: SellText-pl, widget: "markdown", required: true }
  - name: buyPage
    label: BuyPage
    folder: buy-page
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title, required: true  }
      - { name: titleen, label: Title-en, required: true  }
      - { name: titlepl, label: Title-pl, required: true  }
      - { name: subtitle, label: Subtitle, required: true }
      - { name: subtitleen, label: Subtitle-en, required: true }
      - { name: subtitlepl, label: Subtitle-pl, required: true }
      - { label: "BackgroundImage", name: "backgroundImage", widget: "image", required: true }
      - label: 'Products'
        name: "products"
        widget: list
        fields:
          - { label: "productImage", name: "productImage", widget: "image", required: true }
          - { label: "productName", name: "productName", widget: "string", required: true }
          - { label: "productBrand", name: "productBrand", widget: "string", required: true }
          - { label: "productDescription", name: "productDescription", widget: "markdown", required: true }
          - { label: "productDescription-en", name: "productDescriptionen", widget: "markdown", required: true }
          - { label: "productDescription-pl", name: "productDescriptionpl", widget: "markdown", required: true }
          - { label: "productYear", name: "productYear", widget: "number", default: 2020, value_type: "int", required: true }
          - { label: "productCost", name: "productCost", widget: "string", required: true }
  - name: accessoriesPage
    label: AccessoriesPage
    folder: accessories-page
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title, required: true  }
      - { name: titleen, label: Title-en, required: true  }
      - { name: titlepl, label: Title-pl, required: true  }
      - { name: subtitle, label: Subtitle, required: true }
      - { name: subtitleen, label: Subtitle-en, required: true }
      - { name: subtitlepl, label: Subtitle-pl, required: true }
      - { label: "BackgroundImage", name: "backgroundImage", widget: "image", required: true }
      - label: 'Products'
        name: "products"
        widget: list
        fields:
          - { label: "productImage", name: "productImage", widget: "image", required: true }
          - { label: "productName", name: "productName", widget: "string", required: true }
          - { label: "productBrand", name: "productBrand", widget: "string", required: true }
          - { label: "productCost", name: "productCost", widget: "string", required: true }
